//! `oaka compile`: plan + library + templates -> stand-alone scripts in `<workdir>/scripts/`.
//!
//! The scripts never call oaka.  `oaka run` executes exactly these files.

use crate::plan::{self, Checked, ClientSpec, OffSpec, Server, PROMPTS_PER_CONC};
use crate::profile::Arg;
use crate::sys::{self, q};
use anyhow::{Context, Result};
use minijinja::{context, Environment, UndefinedBehavior};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

pub const SCRIPTS: &str = "scripts";
const MARKER: &str = "Generated by oaka";
const READY_TIMEOUT_S: u32 = 1800;
/// pip distributions whose versions every server prints at startup.
const PROVENANCE_PACKAGES: &str = "sglang sgl-kernel sglang-kernel amd-aiter aiter triton torch";

fn templates() -> Result<Environment<'static>> {
    let mut env = Environment::new();
    env.set_undefined_behavior(UndefinedBehavior::Strict);
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.set_keep_trailing_newline(true);
    env.add_filter("q", |v: minijinja::Value| q(&v.to_string()));
    env.add_template("server.sh", include_str!("../templates/server.sh.j2"))?;
    env.add_template("gsm8k.sh", include_str!("../templates/gsm8k.sh.j2"))?;
    env.add_template("fixed_seq.sh", include_str!("../templates/fixed_seq.sh.j2"))?;
    env.add_template("run_all.sh", include_str!("../templates/run_all.sh.j2"))?;
    Ok(env)
}

/// `/<year>/nocopy/InferenceX/inferencex-e2e`, or $OAKA_INFX.
pub fn infx_root() -> String {
    match std::env::var("OAKA_INFX") {
        Ok(p) if !p.is_empty() => p,
        _ => format!("/{}/nocopy/InferenceX/inferencex-e2e", sys::work_year()),
    }
}

/// What the plan changes relative to the server's profile, one line each.
pub fn overrides(s: &Server) -> Vec<String> {
    let (base, eff) = (&s.base, &s.effective);
    let mut out = Vec::new();
    if base.model.as_deref() != Some(s.model.as_str()) {
        out.push(format!("model {}", s.model));
    }
    for (k, v) in &eff.env {
        if !base.env.iter().any(|(bk, bv)| bk == k && bv == v) {
            out.push(format!("env {k}={}", q(v)));
        }
    }
    for (k, _) in &base.env {
        if !eff.env.iter().any(|(ek, _)| ek == k) {
            out.push(format!("env {k} unset"));
        }
    }
    let arg_words = |k: &str, v: &Arg| {
        let mut w = vec![format!("--{k}")];
        match v {
            Arg::Flag => {}
            Arg::Value(s) => w.push(q(s)),
            Arg::List(l) => w.extend(l.iter().map(|s| q(s))),
        }
        w.join(" ")
    };
    for (k, v) in &eff.args {
        if base.arg(k) != Some(v) {
            out.push(format!("args {}", arg_words(k, v)));
        }
    }
    for (k, _) in &base.args {
        if eff.arg(k).is_none() {
            out.push(format!("args --{k} dropped"));
        }
    }
    out
}

pub struct Compiled {
    pub written: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
    pub notes: Vec<String>,
}

pub fn compile(c: &Checked) -> Result<Compiled> {
    let dir = &c.dir;
    let scripts = dir.join(SCRIPTS);
    fs::create_dir_all(&scripts).with_context(|| format!("creating {}", scripts.display()))?;
    let env = templates()?;
    let mut notes = Vec::new();

    // Ports: the plan's, else the lock's (kept even when busy: that is usually this
    // plan's own server, started by hand), else a fresh random one.
    let mut lock = plan::load_lock(dir)?;
    lock.port.retain(|name, _| c.servers.iter().any(|s| s.name == *name));
    let mut ports: Vec<(String, u16)> = Vec::new();
    for s in &c.servers {
        let taken: Vec<u16> = ports
            .iter()
            .map(|(_, p)| *p)
            .chain(c.servers.iter().filter_map(|o| o.port))
            .collect();
        let port = match (s.port, lock.port.get(&s.name)) {
            (Some(p), _) => {
                lock.port.remove(&s.name);
                p
            }
            (None, Some(p)) if !taken.contains(p) => *p,
            _ => {
                let p = sys::pick_port(&taken).context("no free port in 29900-30050")?;
                lock.port.insert(s.name.clone(), p);
                notes.push(format!("server {}: picked port {p}", s.name));
                p
            }
        };
        if !sys::port_free(port) {
            notes.push(format!(
                "server {}: port {port} is in use right now (already running?)",
                s.name
            ));
        }
        ports.push((s.name.clone(), port));
    }
    let port_of = |name: &str| ports.iter().find(|(n, _)| n == name).map(|(_, p)| *p).unwrap();

    let marker = format!(
        "{MARKER} {} from {} at {}.  Edit plan.toml and recompile instead of editing this file.",
        sys::VERSION,
        dir.join(plan::PLAN).display(),
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S")
    );
    let mut files: Vec<(String, String)> = Vec::new();

    for s in &c.servers {
        let file = format!("server_{}.sh", s.name);
        let args: Vec<String> = s
            .effective
            .launch_args()
            .iter()
            .map(|w| w.iter().map(|x| q(x)).collect::<Vec<_>>().join(" "))
            .collect();
        let gpus: Vec<String> = s.gpus.iter().map(u32::to_string).collect();
        let text = env.get_template("server.sh")?.render(context! {
            marker, name => s.name, profile => s.base.name, description => s.base.description,
            overrides => overrides(s), self_path => format!("{SCRIPTS}/{file}"),
            port => port_of(&s.name), gpus => gpus.join(","), env => s.effective.env,
            model => s.model, tp => s.tp, args, packages => PROVENANCE_PACKAGES,
        })?;
        files.push((file, text));
    }

    let mut clients = Vec::new();
    for (i, cl) in c.plan.clients.iter().enumerate() {
        let index = format!("{:02}", i + 1);
        let s = c.servers.iter().find(|s| s.name == cl.server()).unwrap();
        let file = format!("client_{index}_{}_{}.sh", cl.kind(), s.name);
        let out = format!("results/{index}_{}_{}", cl.kind(), s.name);
        let common = context! {
            marker, index, server => s.name, port => port_of(&s.name), served => s.served_name(),
            out, self_path => format!("{SCRIPTS}/{file}"),
        };
        let text = match cl {
            ClientSpec::Gsm8k {
                thinking, min_score, ..
            } => env
                .get_template("gsm8k.sh")?
                .render(context! { thinking, min_score => format!("{min_score:.2}"), ..common })?,
            ClientSpec::FixedSeq {
                isl_osl,
                conc,
                range_ratio,
                repeats,
                off_spec,
                ..
            } => {
                let ppc = match off_spec {
                    Some(OffSpec {
                        prompts_per_conc: Some(n),
                    }) => *n,
                    _ => PROMPTS_PER_CONC,
                };
                let offspec = ppc != PROMPTS_PER_CONC;
                let points: Vec<String> = isl_osl
                    .iter()
                    .flat_map(|[i, o]| conc.iter().map(move |c| format!("{i} {o} {c}")))
                    .collect();
                env.get_template("fixed_seq.sh")?.render(context! {
                    points, repeats, range_ratio, prompts_per_conc => ppc, offspec,
                    spec_prompts_per_conc => PROMPTS_PER_CONC, suffix => if offspec { "_OFFSPEC" } else { "" },
                    tokenizer => s.model, infx => infx_root(), ..common
                })?
            }
        };
        clients.push(file.clone());
        files.push((file, text));
    }

    let servers: Vec<&str> = c.servers.iter().map(|s| s.name.as_str()).collect();
    let text = env.get_template("run_all.sh")?.render(context! {
        marker, self_path => format!("{SCRIPTS}/run_all.sh"), plan => dir.join(plan::PLAN).display().to_string(),
        version => sys::VERSION, servers, clients, ready_timeout_s => READY_TIMEOUT_S,
    })?;
    files.push(("run_all.sh".into(), text));

    // Remove scripts an earlier compile wrote that this plan no longer has.
    let mut removed = Vec::new();
    for e in fs::read_dir(&scripts)?.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        if files.iter().any(|(f, _)| *f == name) || !generated(&e.path()) {
            continue;
        }
        fs::remove_file(e.path())?;
        removed.push(e.path());
    }

    let mut written = Vec::new();
    for (file, text) in files {
        let path = scripts.join(file);
        fs::write(&path, text).with_context(|| format!("writing {}", path.display()))?;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
        written.push(path);
    }
    plan::save_lock(dir, &lock)?;
    Ok(Compiled {
        written,
        removed,
        notes,
    })
}

fn generated(path: &Path) -> bool {
    fs::read_to_string(path)
        .map(|t| t.lines().nth(1).is_some_and(|l| l.contains(MARKER)))
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profile::Library;

    #[test]
    fn compiles_scripts_that_parse() {
        let root = std::env::temp_dir().join(format!("oaka-compile-{}-{}", std::process::id(), fastrand::u32(..)));
        let lib = Library { root: root.join("lib") };
        let work = root.join("work");
        fs::create_dir_all(lib.profiles_dir().join("m")).unwrap();
        fs::create_dir_all(&work).unwrap();
        fs::write(
            lib.profile_path("m/base"),
            "description = 'base'\nmodel = '/model/m'\n[env]\nSGLANG_USE_AITER = '1'\nGONE = 'x'\n\
             [args]\ntrust-remote-code = true\npage-size = 1\nchunked-prefill-size = 2048\n",
        )
        .unwrap();
        let plan = r#"
[[server]]
name = "a"
profile = "m/base"
gpus = [2, 3]
port = 29950
[server.env]
GONE = false
X = "it's"
[server.args]
page-size = 64
chunked-prefill-size = false
served-model-name = "mm"

[[client]]
kind = "gsm8k"
server = "a"
thinking = true

[[client]]
kind = "fixed-seq"
server = "a"
isl_osl = [[1024, 1024], [8192, 1024]]
conc = [4, 8]
off_spec = { prompts_per_conc = 4 }
"#;
        fs::write(work.join(plan::PLAN), plan).unwrap();
        // A stale generated script and a hand-written one.
        fs::create_dir_all(work.join(SCRIPTS)).unwrap();
        fs::write(
            work.join("scripts/server_old.sh"),
            format!("#!/bin/bash\n# {MARKER} x\n"),
        )
        .unwrap();
        fs::write(work.join("scripts/mine.sh"), "#!/bin/bash\n# by hand\n").unwrap();

        let checked = plan::check_plan(&work, plan::load(&work).unwrap(), &lib, None).unwrap();
        let out = compile(&checked).unwrap();
        assert_eq!(out.written.len(), 4);
        assert_eq!(out.removed, vec![work.join("scripts/server_old.sh")]);
        assert!(work.join("scripts/mine.sh").exists());

        let read = |f: &str| fs::read_to_string(work.join(SCRIPTS).join(f)).unwrap();
        let server = read("server_a.sh");
        assert!(server.contains("PORT=29950\n"));
        assert!(server.contains("export HIP_VISIBLE_DEVICES=2,3\n"));
        assert!(server.contains("export X=\"it's\"\n"));
        assert!(!server.contains("GONE="));
        assert!(server.contains("    --tp 2\n    --port \"$PORT\"\n    --trust-remote-code\n    --page-size 64\n"));
        assert!(!server.contains("--chunked-prefill-size 2048"));
        assert!(server.contains("#   plan override: env GONE unset\n"));
        assert!(server.contains("#   plan override: args --chunked-prefill-size dropped\n"));
        let fixed = read("client_02_fixed-seq_a.sh");
        assert!(fixed.contains("    \"8192 1024 8\"\n"));
        assert!(fixed.contains("--num-prompts $(( 4 * CONC ))"));
        assert!(fixed.contains("_OFFSPEC"));
        assert!(fixed.contains("--model mm "));
        assert!(fixed.contains("--tokenizer /model/m "));
        assert!(read("client_01_gsm8k_a.sh").contains("    --thinking \\\n"));
        let run_all = read("run_all.sh");
        assert!(run_all.contains("start_server a\n"));
        assert!(run_all.contains("bash \"$HERE/client_02_fixed-seq_a.sh\""));

        for f in &out.written {
            let st = std::process::Command::new("bash").arg("-n").arg(f).status().unwrap();
            assert!(st.success(), "bash -n {}", f.display());
        }
        // Recompiling keeps the lock's ports stable.
        fs::write(work.join(plan::PLAN), plan.replace("port = 29950\n", "")).unwrap();
        let checked = plan::check_plan(&work, plan::load(&work).unwrap(), &lib, None).unwrap();
        compile(&checked).unwrap();
        let p1 = plan::load_lock(&work).unwrap().port["a"];
        compile(&checked).unwrap();
        assert_eq!(plan::load_lock(&work).unwrap().port["a"], p1);
        fs::remove_dir_all(root).unwrap();
    }
}
